[package]
name = "ntree"
version = "0.0.3"
authors = ["jxz_211 <jxz_211@163.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
regex = "1.4.2"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]